# DAAN 862 Lesson 2 Assignment 1

In [11]:
import numpy as np

## Question 1

In [12]:
#Create Array 5X5
array = np.random.randn(5, 5)

In [13]:
print(array)

[[ 1.21143311e+00  1.59281176e+00  1.25522138e+00 -7.32116325e-01
   1.77743254e+00]
 [-1.60752744e+00 -6.45668890e-02  1.39470117e+00 -6.69615891e-01
   1.29259279e+00]
 [ 1.15537832e+00 -9.39163332e-01 -1.64728776e-01 -1.27864877e-01
   3.77359878e-01]
 [-1.03922169e+00 -8.56718864e-01  5.64219706e-01 -1.27342911e+00
  -7.07044456e-01]
 [-1.87666327e-01 -1.53599916e-03  2.67898466e-01 -1.58229523e+00
  -9.00540519e-01]]


In [14]:
diagonal_sum = 0  # Initialize sum

In [15]:
# Loop through the indices of the array, we can use i and i for row and column since that is the diagonal position of elements when they are equal
for i in range(5):  # 5x5 array, so range is 5
    diagonal_sum += array[i][i]  # Add the diagonal element

print(f"Sum of diagonal elements: {diagonal_sum}")

Sum of diagonal elements: -1.191832183667726


In [16]:
np.sum(array)

0.03501338843545887

In [22]:
max_value = np.max(array)

In [23]:
print(max_value)

1.777432541777802


In [24]:
min_value = np.min(array)

In [25]:
print(min_value)

-1.60752743745788


## Question 2

In [27]:
A = np.random.randint(0, 1000, size=(10, 10))
print(x)


[[746 805 593 399 878 461  94 177 463 680]
 [962 508 763 278 396 762 345 516 688   5]
 [  1 502   1 518 350 587 535 745 879 958]
 [ 50 341 420 656  88 280 245 904  84 619]
 [630 663 840 357 468  50 765  42  62 127]
 [338 431 133 873 186 308 381 852 866 213]
 [922 888 136 488 181 678 778  13 653  64]
 [977 371 978 773  44 374 787 290 943 100]
 [897 841 688  84 883 234  36 883 755 656]
 [158 565 793 629 235 294 989 971 121 637]]


In [29]:
even_num_count = 0  # Initialize counter

# Loop through the 10x10 array
for i in range(10):
    for j in range(10):
        if A[i, j] % 2 == 0:  # Check if the element is even
            even_num_count += 1  # Increment the counter if it's even

print(f"Number of even numbers in the array: {even_num_count}")


Number of even numbers in the array: 50


In [39]:
array_8x9 = np.random.normal(1, 0.5, size=(8, 9)) # Create a 8x 9 array from a normal dist with mean 1 and std dev 0.5
print(array_8x9)

[[ 1.09446863  0.87347863  1.07942766 -0.22789553  0.93890919  0.41328235
   1.02022494  1.25235495  1.52403049]
 [ 1.22482663  1.24193823  0.69901718  2.07874766  1.42586459  0.88780472
   1.00072297  0.12123423  1.15875887]
 [ 1.43891902  1.20240018  0.44781122  0.45316297  1.68286141  1.67736595
   1.46234802  0.09579942  1.32032822]
 [ 0.76664031  0.99491646  0.46612384  1.13356432  0.2146873   1.47667395
   0.56791097  1.74191918  0.28887878]
 [ 0.79257185  1.07099331  0.86139023  1.20107834  0.82953509  0.74894095
   1.43289104  1.388553    1.26888016]
 [ 1.20150157  1.43816867  1.95476388  1.14083296  1.25695342  1.10139257
   0.6943333   1.18909883  1.26696873]
 [-0.18664673  0.50497357  1.22407777  1.06994319  0.93288578  1.38914273
   1.16062546  1.70688302  0.82183608]
 [ 1.24880581  0.05053246  0.39522126  1.04352787  2.18654391  0.78376239
   1.01162342  1.42895611 -0.06431251]]


In [40]:
total_sum = 0
count = 0

In [41]:
# Loop through the 8x9 array
for i in range(8):
    for j in range(9):
        if (i + j) % 5 == 0:  # Check if (i + j) % 5 == 0
            total_sum += array_8x9[i, j]  # Add the element to the sum
            count += 1  # Count the number of such elements

In [42]:
# Calculate the mean
if count > 0:
    mean_value = total_sum / count
else:
    mean_value = 0  # Handle case where no elements meet the condition

In [43]:
print(f"Mean of elements where (i + j) % 5 == 0: {mean_value}")

Mean of elements where (i + j) % 5 == 0: 0.9738592428578939
